### PR TITLE
Fix for UWP

### PR DESCRIPTION
**Pull request by javieranton-zz**
Added missing line
https://github.com/codenameone/CodenameOne/issues/3400
Should only be a matter of publishing a new version for the CN1Lib now

### CODE REVIEW

**Comment by shannah** [comment]
Thanks.  I have rebuilt and added to Codename One preferences.  The changes should propagate soon, but you can download build now at :

https://github.com/codenameone/CodenameOneLibs/blob/master/cn1libs/CN1AppleSignIn.cn1lib

**Comment by javieranton-zz** [comment]
Thanks will check in 2 hrs

**Comment by javieranton-zz** [comment]
It's fixed; However there were some errors that prevented me from updating or properly installing the latest version of the CN1Lib. I ended up having to manually edit the nativewin.zip file and adding the text to the modified file for this to work

Perhaps something can be learned from the problems I experienced.

First, I tried clicking on "update" in the AppleSignIn Extensions part of CN1 Settings. This resulted in a maven error:

image

I then deleted the CN1AppleSignIn folder within cn1libs and tried to reinstall. However, I wasn't able to do this until I manually removed a duplicate reference to CN1AppleSignIn in cn1libs.pom

After I did that, I proceeded to "Download" the extension. It installed everything and this time the CN1AppleSignIn.cn1lib and CN1AppleSignIn.ver files were also under cn1libs (unlike before)

However, looking at the contents of the AppleSignInNativeImpl.cs in nativewin.zip showed it didin't have the latest changes. Furthermore, CN1AppleSignIn.ver says version 1, and I think it should say version 8?

So anyway, seems to be ok for my purposes but the whole process felt a bit buggy. Maybe it's me and I am not doing something properly.

**Comment by shannah** [comment]
If it didn't have the latest changes, then the update must not have gone through yet (in Codename One Settings).
Manual modification should be fine.  
But you could also explicitly install the cn1lib directly using the cn1:install-cn1lib goal.
https://shannah.github.io/codenameone-maven-manual/#_install_legacy_cn1lib_install_cn1lib

**Comment by javieranton-zz** [comment]
Sounds good thx

**Pull request merged**
